### ISSUE TITLE
XViewSingleDataset KeyError: 'nondamage'

### ISSUE THREAD

**Issue by YaoMufeng** [selimsef/xview2_solution#1]
Hello selimsef
Thank you for your sharing.
I was trying to run your code in my computer, but got KeyError in XViewSingleDataset's init function at this line:
nondamage = df[(df['fold'] != fold) & (df['nondamage'] == True)]['id'].tolist()
error information:

Traceback (most recent call last):
  File "train.py", line 357, in <module>
    main()
  File "train.py", line 123, in main
    normalize=conf["input"].get("normalize", None))
  File "/opt/share1003/public/yaomf/codes/xview2-2/dataset/xview_dataset.py", line 28, in __init__
    nondamage = df[(df['fold'] != fold) & (df['nondamage'] == True)]['id'].tolist()
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1969, in __getitem__
    return self._getitem_column(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1976, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 1091, in _get_item_cache
    values = self._data.get(item)
  File "/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 3211, in get
    loc = self.items.get_loc(item)
  File "/usr/lib/python2.7/dist-packages/pandas/core/index.py", line 1759, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 'nondamage'

I found that df is loaded from csv file, and the csv file contained in your code has only 2 columns: id and fold, without 'nondamage'.

Do I need to generate a csv file in another format in order to run your code at xview2 dataset?
I have downloaded the dataset and generate mask using your script.

Thank you!

**Comment by selimsef** [comment]
Hi, 
Thanks for pointing that out it was wrong folds file. Updated with all columns.
