### ISSUE TITLE
OSError: [Errno 24] Too many open files - Issue with tqdm in the validation phase

### ISSUE THREAD

**Issue by ghost** [selimsef/xview2_solution#8]
Hi,

During validation step, I am facing  the following error which is related to `tqdm`. As I am training on both train and tier3 sets, it seems the a parameter in tqdm library is overflowing.

```bash
Traceback (most recent call last):
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 319, in reduce_storage
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/reduction.py", line 191, in DupFd
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):                                                           
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/resource_sharer.py", line 149, in _serve
Traceback (most recent call last):
  File "train_localization.py", line 301, in <module>
    send(conn, destination_pid)
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/resource_sharer.py", line 50, in send
    main()
  File "train_localization.py", line 206, in main 
    predictions_dir=preds_dir) 
  File "train_localization.py", line 214, in evaluate_val
    dice = validate(model, data_loader=data_val, predictions_dir=predictions_dir)
  File "train_localization.py", line 241, in validate
    reduction.send_handle(conn, new_fd, pid)
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/reduction.py", line 176, in send_handle
    for sample in tqdm(data_loader): 
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/tqdm/std.py", line 1127, in __iter__ 
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:                                                                                     
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/socket.py", line 460, in fromfd 
    for obj in iterable:
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__ 
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
    idx, batch = self._get_batch() 
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch 
    success, data = self._try_get_batch()                                                                                                        
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/majid/anaconda3/envs/xV2-con36-cu90-tch110-tv030/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
```

I tried the following ways to solve it:

I increased `ulimit -n` from 1024 to 4096.
In `train.py` and `train_localization.py`, in the function 
`def validate(net, data_loader, predictions_dir):`
, I replaced 
`for sample in tqdm(data_loader):` 
with 
```
with tqdm(data_loader) as samples:
            for i,  sample in enumerate(samples): 
```

, but none of these ways was a solution.

I was wondering whether you would have a solution for this. I am still looking around for a solution.

**Comment by ghost** [comment]
I realized I had to increase ulimit -n even further. Now it is training. Thanks !
